EduErp.Web/Controllers/NotificationController.cs
using System;
using System.Web.Mvc;
using EduErp.BLL;
using EduErp.BO;
using EduErp.Common;
using EduErp.Mvc.Utilities;

namespace EduErp.Web.Controllers
{
    public class NotificationController : BaseController
    {
        //
        // GET: /Notification/

        public ActionResult Index()
        {
            return View(NotificationService.GetNotificationsForIndex().Result);
        }
        [AjaxOnly]
        public ActionResult Add()
        {
            NotificationBo model = new NotificationBo
            {
                ListOfNotifications = NotificationService.GetNotifications().Result
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(NotificationBo model)
        {
            if (!ModelState.IsValid)
                return View(model);
            model.ListOfNotifications = NotificationService.GetNotifications().Result;
            model.SchoolId = SessionItems.SchoolId;
            model.CreatedBy = SessionItems.UserId;
            model.CreatedOn = DateTime.Now;
            model.StatusId = (int)UserStatus.Active;
            var result = NotificationService.AddNotification(model).Result;
            if (result)
                TempData["SuccessMessage"] = Messages.AddSuccessfully;
            else
                TempData["ErrMessage"] = Messages.AddError;
            return Json(new { isErr = false, msg = Messages.AddSuccessfully }, JsonRequestBehavior.AllowGet);
        }

        [AjaxOnly]
        public ActionResult Edit(int id)
        {
            var result = NotificationService.GetNotificationById(id).Result;
            result.ListOfNotifications = NotificationService.GetNotifications().Result;
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NotificationBo model)
        {
            if (!ModelState.IsValid)
                return View(model);
            model.UpdatedBy = SessionItems.UserId;
            model.UpdatedOn = DateTime.Now;
            model.ListOfNotifications = NotificationService.GetNotifications().Result;
            var result = NotificationService.UpdateNotification(model).Result;
            if (result)
                TempData["SuccessMessage"] = Messages.UpdateSuccessfully;
            else
                TempData["ErrMessage"] = Messages.UpdateError;
            return Json(new { isErr = false, msg = Messages.UpdateSuccessfully }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult UpdateStatus(int id, int statusId)
        {
            var result = NotificationService.UpdateStatus(id, statusId, SessionItems.UserId).Result;
            if (result)
                TempData["SuccessMessage"] = Messages.UpdateSuccessfully;
            else
                TempData["ErrMessage"] = Messages.UpdateError;
            return Json(result);
        }

    }
}

EduErp.Web/Views/Notification/Add.cshtml
@model EduErp.BO.NotificationBo
<div class="modal fade in" id="addFranchiseModal" style="display: block;" aria-hidden="false">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button data-dismiss="modal" class="close" type="button">
                ×
            </button>
            <h4 class="modal-title">
                <span id="franchiseModalTitle">Add New Notification </span>
            </h4>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("Add", "Notification", null, FormMethod.Post, new {data_validate = "parsley", @autocomplete = "off", @id = "addnotice"}))
            {
                @Html.AntiForgeryToken()
                ;
                <div class="panel-body">
                    <div class=" pull-in clearfix">
                        <div class="form-group col-md-6">
                            @Html.Label("Subject")
                            @Html.TextBoxFor(u => u.Subject, new {@class = "form-control", maxlength = "50"})
                        </div>
                        <div class="form-group col-md-6">
                            @Html.Label("Notification Type")
                            @Html.DropDownListFor(m => m.NoticeTypeId, new SelectList(Model.ListOfNotifications, "Id", "Name"),"Please Select", new {@class = "form-control"})
                        </div>
                        <div class="form-group col-md-12">
                            @Html.Label("Description")
                            @Html.TextAreaFor(m=>m.Description,new{@class="form-control"})
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="btnAddSession" type="button" class="btn btn-lightGreen btn-s-xs" onclick=" saveForm(); ">
                        <i class="fa fa-save"></i>&nbsp;Save
                    </button>
                    <a data-dismiss="modal" class="btn btn-default" href="#">Cancel</a>
                </div>
            }
        </div>
    </div>
    <!-- /.modal-content -->
</div>
    </div>

<script>

    function saveForm() {
        debugger;
        $('#addnotice').parsley().validate();
        if ($('#addnotice').parsley().isValid()) {
            var token = $('input[name="__RequestVerificationToken"]').val();
            var headers = {};
            headers['__RequestVerificationToken'] = token;
            $.ajax({
                url: '@Url.Action("Add", "Notification")',
                data: $("#addnotice").serialize(),
                type: 'post',
                headers: headers,
                success: function (data) {
                    if (data.isErr) {
                        toastr.error(data.errMsg);
                        return;
                    }
                    window.location.href = '@Url.Action("Index", "Notification")';
                }
            });
        }
        else {
            toastr.error("Mandatory fields are required");
        }
    }
</script>

EduErp.Web/Views/Notification/Edit.cshtml
@model EduErp.BO.NotificationBo
<div class="modal fade in" id="addFranchiseModal" style="display: block;" aria-hidden="false">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button data-dismiss="modal" class="close" type="button">
                ×
            </button>
            <h4 class="modal-title">
                <span id="franchiseModalTitle">Update Notification </span>
            </h4>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("Edit", "Notification", null, FormMethod.Post, new {data_validate = "parsley", @autocomplete = "off", @id = "editnotice"}))
            {
                @Html.AntiForgeryToken()
                ;
                <div class="panel-body">
                    <div class=" pull-in clearfix">
                        <div class="form-group col-md-6">
                            @Html.Label("Subject")
                            @Html.TextBoxFor(u => u.Subject, new {@class = "form-control", maxlength = "50"})
                        </div>
                        <div class="form-group col-md-6">
                            @Html.Label("Notification Type")
                            @Html.DropDownListFor(m => m.NoticeTypeId, new SelectList(Model.ListOfNotifications, "Id", "Name"),"Please Select", new {@class = "form-control"})
                        </div>
                        <div class="form-group col-md-12">
                            @Html.Label("Description")
                            @Html.TextAreaFor(m=>m.Description,new{@class="form-control"})
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="btnAddSession" type="button" class="btn btn-lightGreen btn-s-xs" onclick=" validateForm(); ">
                        <i class="fa fa-save"></i>&nbsp;Update
                    </button>
                    <a data-dismiss="modal" class="btn btn-default" href="#">Cancel</a>
                </div>
            }
        </div>
    </div>
    <!-- /.modal-content -->
</div>
    </div>

<script>

    function validateForm() {
        debugger;
        $('#editnotice').parsley().validate();
        if ($('#editnotice').parsley().isValid()) {
            var token = $('input[name="__RequestVerificationToken"]').val();
            var headers = {};
            headers['__RequestVerificationToken'] = token;
            $.ajax({
                url: '@Url.Action("Edit", "Notification")',
                data: $("#editnotice").serialize(),
                type: 'post',
                headers: headers,
                success: function (data) {
                    if (data.isErr) {
                        toastr.error(data.errMsg);
                        return;
                    }
                    window.location.href = '@Url.Action("Index", "Notification")';
                }
            });
        }
        else {
            toastr.error("Mandatory fields are required");
        }
    }
</script>

EduErp.Web/Views/Notification/Index.cshtml
@using EduErp.BO
@using EduErp.BO.Enumerators
@using EduErp.Mvc.Utilities
@model List<EduErp.BO.NotificationBo>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_GridLayout.cshtml";
}

<header class="panel-heading font-bold b-light">
    Notifications
    @if (SessionItems.UserRights.Any(a => a.MenuId == (int) MenuMasters.Notification) && SessionItems.UserRights.Any(a => a.RightId == (int) Right.Write))
    {
        <a href="@Url.Action("Add", "Notification")" class="btn-sm btn-primary pull-right" ajax-modal="ajaxModal"><i class="fa fa-plus"></i>&nbsp;Add Notification</a>
    }
</header>
@Html.AntiForgeryToken()
<section class="scrollable w-f">
    <div class="row">
        <div class="col-md-12">
            <section class="panel panel-default">
                <div class="table-responsive">
                    <table id="dt_userList" width="100%" class="table table-striped"  title="Notification" exportcolumn="0,1,2,3" visiblecolumn="0,1,2,3,4,5" lastunsortcount="2">
                        <thead>
                            <tr>
                                <th class="text-center">Subject
                                </th>
                                <th class="text-center">Description
                                </th>
                                <th class="text-center">Notification Type
                                </th>
                               <th class="text-center">Status
                                </th>
                                @if (SessionItems.UserRights.Any(a => a.MenuId == (int) MenuMasters.Notification) && SessionItems.UserRights.Any(a => a.RightId == (int) Right.Write))
                                 {
                                     
                                    <th class="text-center">Edit
                                     </th>
                                     <th class="text-center">Delete
                                     </th>

                                 }
                            </tr>
                        </thead>
                        <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                            <tr>

                                @*<td class="text-center">
                                        @Html.DisplayFor(model => item.Id)
                                    </td>*@
                                <td class="text-center">
                                    @Html.DisplayFor(model => item. Subject)
                                </td>

                                <td class="text-center">
                                    @Html.DisplayFor(model => item.Description)
                                </td>
                                <td class="text-center">
                                   @item.NotificationTypeName
                                </td>
                               <td class="text-center">
                                    <button class="btn btn-default @(item.StatusId == (int)UserStatus.Active ? "btn-success active" : "")" title="@(item.StatusId == (int)UserStatus.Active ? "Click to deactivate" : "Click to activate")" data-container="body" data-toggle="toolTip"
                                            id="@item.Id" onclick=" setStatusConfirmation(updateStatus, '@(item.Id == (int)UserStatus.Active ? "Deactivate Notification" : "Activate Notification")', '@(item.StatusId == (int)UserStatus.Active ? "Are you sure you want to deactivate Notification" : "Are you sure you want to activate Notification ")', '@item.Id', '@(item.StatusId == (int)UserStatus.Active ? (int)UserStatus.InActive : (int)UserStatus.Active)') ">
                                        <i class="fa @(item.StatusId == (int)UserStatus.Active ? "fa-check text-active" : "fa-times text-danger")"></i>
                                        <span class=@(item.StatusId == (int)UserStatus.Active ? "text-active" : "text")>@(item.StatusId == (int)UserStatus.Active ? "Active" : "Inactive")</span>
                                    </button>
                                </td>
                                @if ((SessionItems.UserRights.Any(a => a.MenuId == (int)MenuMasters.Message) && SessionItems.UserRights.Any(a => a.RightId == (int)Right.Write)) && (item.StatusId == (int)UserStatus.Active))
                                {

                                    <td class="text-center">
                                            <a href="@Url.Action("Edit", "Notification", new { @id = item.Id })" id="btnModalOpen" title="Edit" data-placement="top" data-container="body" ajax-modal="ajaxModal">
                                                <i class="fa fa-edit icon"></i>&nbsp;Edit
                                            </a>
                                        </td>
                                    
                                    <td class="text-center">
                                        <a title="Delete" data-placement="top" data-container="body" onclick=" deleteConfirmation(updateStatus, '@item.Id', '@((int)UserStatus.Deleted)') ">
                                            <i class=" fa fa-trash-o text-danger">
                                            </i>&nbsp;Delete
                                        </a>
                                    </td>
                                }
                            </tr>
                            }
                        }
                        </tbody>
                    </table>
                </div>
            </section>
        </div>
    </div>
</section>

<script type="text/javascript">
    $(document).ready(function () {
        var exportColumns = $("#dt_userList > thead > tr > th").length;
        //console.log(exportColumns);
        var aTargets = [];
        for (var i = 0; i < exportColumns; i++) {
            aTargets.push(i * 1);
        }
        var visibleColumns = $("#dt_userList > thead > tr > th:not(.hidden)").length;
        //console.log(visibleColumns);
        var vTargets = [];
        for (var j = 0; j < visibleColumns; j++) {
            vTargets.push(j * 1);
        }
        $("#dt_userList").attr("exportColumn", aTargets);
        $("#dt_userList").attr("visibleColumn", vTargets);
        refreshGrid('dt_userList');
    });
    function updateStatus(id, statusId) {
        debugger;
        var token = $('input[name="__RequestVerificationToken"]').val();
        $.ajax({
            url: '@Url.Action("UpdateStatus","Notification")',
            data: { Id: id, statusId: statusId, "__RequestVerificationToken": token },
            type: 'post',
            success: function(data) {
                location.reload();
            }

        });

    }

</script>