EduErp.Web/Controllers/AccountDetailController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using EduErp.BLL;
using EduErp.BO;
using EduErp.Common;
using EduErp.Mvc.Utilities;

namespace EduErp.Web.Controllers
{
    public class AccountDetailController : BaseController
    {
        //
        // GET: /AccountDetail/

        public ActionResult Index()
        {
            return View(AccountDetailService.GetAccountDetail().Result);
        }

        public ActionResult Add()
        {
            AccountDetailBo model = new AccountDetailBo
            {
                ListOfSchools = Schools,
                ListOfPlans = AccountDetailService.GetPlan().Result,
                ListOfDays = AccountDetailService.GetDay().Result
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(AccountDetailBo model)
        {

            model.WeeklyHolidays = string.Join(",", model.ListOfDays.Where(a => a.Selected).Select(b => b.DayId).ToArray());

            //DateTime npdate;
            //DateTime.TryParseExact(model.NextPaymentDateStr, "dd-MMM-yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out npdate);
            //model.NextPaymentDate = npdate;

            //DateTime apdate;
            //DateTime.TryParseExact(model.AppStartDateStr, "dd-MMM-yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out apdate);
            //model.AppStartDate = apdate;

            //DateTime duedate;
            //DateTime.TryParseExact(model.DueDateStr, "dd-MMM-yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out duedate);
            //model.DueDate = duedate;
            if (!ModelState.IsValid) return View(model);
            model.ListOfSchools = Schools;
            model.ListOfPlans = AccountDetailService.GetPlan().Result;
            model.CreatedBy = SessionItems.UserId;
            model.CreatedOn = DateTime.Now;
            model.StatusId = (int)UserStatus.Active;
            var result = AccountDetailService.AddAcountDetail(model).Result;
            if (result)
                TempData["SuccessMessage"] = Messages.AddSuccessfully;
            else
                TempData["ErrMessage"] = Messages.AddError;
            return Json(new { isErr = false, msg = Messages.AddSuccessfully }, JsonRequestBehavior.AllowGet);

        }


        public ActionResult Edit(int id)
        {
            var model = AccountDetailService.GetAccountDetailById(id).Result;
            model.ListOfSchools = Schools;
            model.ListOfPlans = AccountDetailService.GetPlan().Result;
            if (model.NextPaymentDate != null)
                model.NextPaymentDateStr = model.NextPaymentDate.Value.ToFormattedDate();
            if (model.DueDate != null)
                model.DueDateStr = model.DueDate.Value.ToFormattedDate();
            if (model.AppStartDate != null)
                model.AppStartDateStr = model.AppStartDate.Value.ToFormattedDate();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AccountDetailBo model)
        {
            //DateTime adate;
            //DateTime.TryParseExact(model.AppStartDateStr, "dd-MMM-yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out adate);
            //model.AppStartDate = adate;
            //DateTime npdate;
            //DateTime.TryParseExact(model.NextPaymentDateStr, "dd-MMM-yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out npdate);
            //model.NextPaymentDate = npdate;
            //DateTime duedate;
            //DateTime.TryParseExact(model.DueDateStr, "dd-MMM-yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out duedate);
            //model.DueDate = duedate;
            if (!ModelState.IsValid) return View(model);
            model.ListOfSchools = Schools;
            model.ListOfPlans = AccountDetailService.GetPlan().Result;
            model.UpdatedBy = SessionItems.UserId;
            model.UpdatedOn = DateTime.Now;
            var result = AccountDetailService.UpdateAccountDetail(model).Result;
            if (result)
                TempData["SuccessMessage"] = Messages.UpdateSuccessfully;
            else
                TempData["ErrMessage"] = Messages.AddError;
            return Json(new { isErr = false, msg = Messages.UpdateSuccessfully }, JsonRequestBehavior.AllowGet);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult UpdateStatus(int id, int statusId)
        {
            var result = AccountDetailService.UpdateStatus(id, statusId, SessionItems.UserId).Result;
            if (result)
                TempData["SuccessMessage"] = Messages.UpdateSuccessfully;
            else
                TempData["ErrMessage"] = Messages.UpdateError;
            return Json(result);
        }
    }
}

EduErp.Web/Views/AccountDetail/Add.cshtml
@using EduErp.Mvc.Utilities
@using EduErp.BO
@model EduErp.BO.AccountDetailBo
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="panel panel-default scrollable">
    <header class="panel-heading font-bold">
        <div class="row">
            <div class="col-md-12">
                Add AccountDetail
            </div>
        </div>
    </header>
    @using (Html.BeginForm("Add", "AccountDetail", FormMethod.Post, new {enctype = "multipart/form-data", data_validate = "parsley", id = "addAccountDetailForm"}))
    {
        @Html.AntiForgeryToken()
        <div style="padding-top: 5px">
            <p style="margin-left: 12px">Fields with <span class="text-danger">*</span> are required.
            </p>
        </div>

        <div class="panel-body">
            <div class="pull-in clearfix">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group col-md-3 col-sm-3">
                            @Level.GetlabelName((int)LabelEnum.School)&nbsp;<span class="text-danger">*</span>
                            @Html.DropDownListFor(m => m.SchoolId, new SelectList(Model.ListOfSchools, "Value", "Text"), "Please Select", new {@class = "form-control"})
                        </div>
                        <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Due Date")
                            @Html.TextBoxFor(m => m.DueDate, new {@class = "form-control datepicker-input", data_date_format = "dd-mm-yyyy"})
                        </div>

                        <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Next Payment tDate")
                            @Html.TextBoxFor(m => m.NextPaymentDate, new {@class = "form-control datepicker-input", data_date_format = "dd-mm-yyyy "})
                        </div>
                         <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("App Start Date")
                            @Html.TextBoxFor(m => m.AppStartDate, new {@class = "form-control datepicker-input", data_date_format = "dd-mm-yyyy"})
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                       
                        <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Plan")
                            @Html.DropDownListFor(m => m.PlanId, new SelectList(Model.ListOfPlans, "Id", "Name"), "Please Select", new {@class = "form-control"})
                        </div>
                        <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Left Student")
                            @Html.TextBoxFor(m => m.LeftStudentCount, new {@class = "form-control"})
                        </div>
                        <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Left Message")
                            @Html.TextBoxFor(m => m.LeftMessageCount, new {@class = "form-control"})
                        </div>
                         <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Left User")
                            @Html.TextBoxFor(m => m.LeftUserCount, new {@class = "form-control"})
                        </div>
                    </div>
                </div>

                 <div class="form-group col-md-12  col-sm-12 col-xs-12">
                                    <div class="btn-group" style="padding-top: 20px">
                                        <label class="btn btn-default">
                                            <span>
                                                <input type="checkbox" id="allcheck">
                                            </span>
                                        </label>
                                        <label class="[ btn btn-primary active ]">
                                            @Html.Label("Select All Weekly Holiyays")
                                        </label>
                                        <br/>
                                    </div>
                                </div>
                                @for (var i = 0; i < Model.ListOfDays.Count; i++)
                                {
                                    var mid = "ListOfDays_" + i + "__Selected";
                                    //var ddid = "ListOfMonths_" + i + "__MonthId";

                                    <div class="form-group col-md-4">
                                        @Html.HiddenFor(m => Model.ListOfDays[i].DayId)
                                        @Html.HiddenFor(m => Model.ListOfDays[i].Selected)
                                        @Html.HiddenFor(m => Model.ListOfDays[i].DayName)
                                        @*<input id="@t.Id fancy-checkbox-default" name="@t.Name fancy-checkbox-default" type="checkbox" value="@t.Name" autocomplete="off"/>*@
                                        <div class="btn-group">
                                            <label class="btn btn-default">
                                                <span>
                                                    <input id="@mid" class="checkitem" name="@mid" type="checkbox" value="@Model.ListOfDays[i].Selected" @(Model.ListOfDays[i].Selected ? "checked='checked'" : "") autocomplete="off"/>
                                                </span>
                                            </label>
                                            <label class="btn btn-primary active">
                                                @Model.ListOfDays[i].DayName
                                            </label>
                                            <br/>
                                        </div>
                                       </div>
                                }
            </div>
        </div>

        <footer class="panel-footer text-right bg-white lter">
            <button id="btnAddAccountDetail" type="button" class="btn btn-lightGreen btn-s-xs" onclick=" saveForm(); ">
                <i class="fa fa-save"></i>&nbsp;Save
            </button>
            <a href="@Url.Action("Index", "AccountDetail")" class="btn btn-s-md  btn-default">
                <i class="fa fa-ban"></i>&nbsp;Cancel
            </a>
        </footer>
    }
</section>
<<script src="~/Content/js/bootstap-datepicker/bootstrap-datepicker.min.js"></script>
<link href="~/Content/js/bootstap-datepicker/bootstrap-datepicker.min.css" type="text/css" rel="stylesheet"/>
<script type="text/javascript">
    $(document).ready(function () {
        $("input:checkbox.checkitem").click(function () {
            debugger;
            if ($(this).is(':checked')) {
                $("#" + $(this).attr('id')).val(true);
                if ($(".checkitem:checked").length === $('input:checkbox.checkitem').length) {
                    $("#allcheck").prop("checked", true);
                }
            } else {
                $("#" + $(this).attr('id')).val(false);
                $("#allcheck").prop("checked", false);
            }
        });

        $("#allcheck").change(function () {
            $(".checkitem").each(function (index) {
                debugger;
                $(".checkitem").prop("checked", $("#allcheck").prop("checked"));
                $("#" + $(this).attr('id')).val($("#allcheck").prop("checked"));
            });
            });

        $('.chosen-select').chosen({
            search_contains: true
        });
        var currentDate = getFormattedDate(new Date());
        $('.datepicker-input').datepicker({
            format: CURRENT_DATEFORMAT,
            //startDate: currentDate,
            autoclose: true
        }).on('changeDate', function (ev) {
            if ($(".datepicker-input").hasClass("parsley-error")) {
                $(".datepicker-input").parsley().reset();
            }
        });
        $(".datepicker-input").val('');


    });

    function saveForm() {
        debugger;
        $('#addAccountDetailForm').parsley().validate();
        if ($('#addAccountDetailForm').parsley().isValid()) {
            var token = $('input[name="__RequestVerificationToken"]').val();
            var headers = {};
            headers['__RequestVerificationToken'] = token;
            $.ajax({
                url: '@Url.Action("Add", "AccountDetail")',
                data: $("#addAccountDetailForm").serialize(),
                type: 'post',
                headers: headers,
                success: function (data) {
                    if (data.isErr) {
                        toastr.error(data.errMsg);
                        return;
                    }
                    window.location.href = '@Url.Action("Index", "AccountDetail")';
                }
            });
        }
        else {
            toastr.error("Mandatory fields are required");
        }
    }
</script>

EduErp.Web/Views/AccountDetail/Edit.cshtml
@using EduErp.BO
@using EduErp.Mvc.Utilities
@model EduErp.BO.AccountDetailBo
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="panel panel-default scrollable">
    <header class="panel-heading font-bold">
        <div class="row">
            <div class="col-md-12">
                Edit AccountDetail
            </div>
        </div>
    </header>
    @using (Html.BeginForm("Edit", "AccountDetail", FormMethod.Post, new { enctype = "multipart/form-data", data_validate = "parsley", id = "editAccountDetailForm" }))
    {
        @Html.AntiForgeryToken()
        <div style="padding-top: 5px">
            <p style="margin-left: 12px">Fields with <span class="text-danger">*</span> are required.
            </p>
        </div>

        <div class="panel-body">
            <div class="pull-in clearfix">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group col-md-3 col-sm-3">
                            @Level.GetlabelName((int)LabelEnum.School)&nbsp;<span class="text-danger">*</span>
                            @Html.DropDownListFor(m => m.SchoolId, new SelectList(Model.ListOfSchools, "Value", "Text"), "Please Select", new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Due Date")
                            @Html.TextBoxFor(m => m.DueDate, new { @class = "form-control datepicker-input", data_date_format = "dd-mm-yyyy" })
                        </div>

                        <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Next Payment tDate")
                            @Html.TextBoxFor(m => m.NextPaymentDate, new { @class = "form-control datepicker-input", data_date_format = "dd-mm-yyyy " })
                        </div>
                         <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("App Start Date")
                              @Html.TextBoxFor(m => m.AppStartDate, new { @class = "form-control datepicker-input", data_date_format = "dd-mm-yyyy" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                      
                        <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Plan")
                            @Html.DropDownListFor(m => m.PlanId, new SelectList(Model.ListOfPlans, "Id", "Name"), "Please Select", new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Left Student")
                            @Html.TextBoxFor(m => m.LeftStudentCount, new {@class = "form-control"})
                        </div>
                        <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Left Message")
                            @Html.TextBoxFor(m => m.LeftMessageCount, new {@class = "form-control"})
                        </div>
                         <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Left User")
                            @Html.TextBoxFor(m => m.LeftUserCount, new {@class = "form-control"})
                        </div>
                    </div>
                </div>
                </div>
        </div>

        <footer class="panel-footer text-right bg-white lter">
            <button id="btnAddAccountDetail" type="button" class="btn btn-lightGreen btn-s-xs" onclick=" validateForm(); ">
                <i class="fa fa-save"></i>&nbsp;Save
            </button>
            <a href="@Url.Action("Index", "AccountDetail")" class="btn btn-s-md  btn-default">
                <i class="fa fa-ban"></i>&nbsp;Cancel
            </a>
        </footer>
    }
</section>
<<script src="~/Content/js/bootstap-datepicker/bootstrap-datepicker.min.js"></script>
<link href="~/Content/js/bootstap-datepicker/bootstrap-datepicker.min.css" type="text/css" rel="stylesheet"/>
<script type="text/javascript">
    $(document).ready(function () {
        $('.chosen-select').chosen({
            search_contains: true
        });
        var currentDate = getFormattedDate(new Date());
        $('.datepicker-input').datepicker({
            format: CURRENT_DATEFORMAT,
            //startDate: currentDate,
            autoclose: true
        }).on('changeDate', function (ev) {
            if ($(".datepicker-input").hasClass("parsley-error")) {
                $(".datepicker-input").parsley().reset();
            }
        });
       // $(".datepicker-input").val('');


    });

    function validateForm() {
        debugger;
        $('#editAccountDetailForm').parsley().validate();
        if ($('#editAccountDetailForm').parsley().isValid()) {
            var token = $('input[name="__RequestVerificationToken"]').val();
            var headers = {};
            headers['__RequestVerificationToken'] = token;
            $.ajax({
                url: '@Url.Action("Edit", "AccountDetail")',
                data: $("#editAccountDetailForm").serialize(),
                type: 'post',
                headers: headers,
                success: function (data) {
                    if (data.isErr) {
                        toastr.error(data.errMsg);
                        return;
                    }
                    window.location.href = '@Url.Action("Index", "AccountDetail")';
                }
            });
        }
        else {
            toastr.error("Mandatory fields are required");
        }
    }
</script>

EduErp.Web/Views/AccountDetail/Index.cshtml
@using EduErp.BO
@using EduErp.BO.Enumerators
@using EduErp.Mvc.Utilities
@model List<EduErp.BO.AccountDetailBo>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_GridLayout.cshtml";
}

<header class="panel-heading font-bold b-light">
    Add AccountDetail
    @if (SessionItems.UserRights.Any(a => a.MenuId == (int)MenuMasters.AccountDetail) && SessionItems.UserRights.Any(a => a.RightId == (int)Right.Write))
    {
        <a href="@Url.Action("Add", "AccountDetail")" class="btn-sm btn-primary pull-right"><i class="fa fa-plus"></i>&nbsp;Account Detail</a>
    }
</header>

@Html.AntiForgeryToken()
<section class="scrollable w-f">
    <div class="row">
        <div class="col-md-12">
            <section class="panel panel-default">
                <div class="table-responsive">
                    <table id="dt_userList" width="100%" class="table table-striped"  title="Messages" exportcolumn="0,1,2,3,4" visiblecolumn="0,1,2,3,4,5,6" lastunsortcount="2">
                        <thead>
                            <tr>
                                <th class="text-center"> @Level.GetlabelName((int)LabelEnum.School) Name
                                </th>
                                <th class="text-center">Left Student(s) 
                                </th>
                                <th class="text-center">Left Message(s)
                                </th>
                                <th class="text-center">Left User(s)
                                </th>
                                <th class="text-center">Due Date
                                </th>
                                 <th class="text-center">Next Payment Date
                                </th>
                                <th class="text-center">Status
                                </th>
                                @if (SessionItems.UserRights.Any(a => a.MenuId == (int)MenuMasters.AccountDetail) && SessionItems.UserRights.Any(a => a.RightId == (int)Right.Write))
                                {
                                     
                                     <th class="text-center">Edit
                                     </th>
                                     <th class="text-center">Delete
                                     </th>

                                }
                            </tr>
                        </thead>
                        <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                            <tr>

                                @*<td class="text-center">
                                        @Html.DisplayFor(model => item.Id)
                                    </td>*@
                                <td class="text-center">
                                    @Html.DisplayFor(model => item.SchoolName)
                                </td>

                                <td class="text-center">
                                    @Html.DisplayFor(model => item.LeftStudentCount)
                                </td>
                                 <td class="text-center">
                                    @Html.DisplayFor(model => item.LeftMessageCount)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(model => item.LeftUserCount)
                                </td>
                                <td class="text-center">
                                    @if (item.DueDate != null)
                                    {
                                        @item.DueDate.Value.ToFormattedDate()
                                    }
                                </td>
                                 <td class="text-center">
                                    @if (item.NextPaymentDate != null)
                                    {
                                        @item.NextPaymentDate.Value.ToFormattedDate()
                                    }
                                </td>
                               <td class="text-center">
                                    <button class="btn btn-default @(item.StatusId == (int)UserStatus.Active ? "btn-success active" : "")" title="@(item.StatusId == (int)UserStatus.Active ? "Click to deactivate" : "Click to activate")" data-container="body" data-toggle="toolTip"
                                            id="@item.Id" onclick=" setStatusConfirmation(updateStatus, '@(item.Id == (int)UserStatus.Active ? "Deactivate AccountDetail" : "Activate AccountDetail")', '@(item.StatusId == (int)UserStatus.Active ? "Are you sure you want to deactivate Account Detail" : "Are you sure you want to activate Account Detail ")', '@item.Id', '@(item.StatusId == (int)UserStatus.Active ? (int)UserStatus.InActive : (int)UserStatus.Active)') ">
                                        <i class="fa @(item.StatusId == (int)UserStatus.Active ? "fa-check text-active" : "fa-times text-danger")"></i>
                                        <span class=@(item.StatusId == (int)UserStatus.Active ? "text-active" : "text")>@(item.StatusId == (int)UserStatus.Active ? "Active" : "Inactive")</span>
                                    </button>
                                </td>
                                @if ((SessionItems.UserRights.Any(a => a.MenuId == (int)MenuMasters.AccountDetail) && SessionItems.UserRights.Any(a => a.RightId == (int)Right.Write)) && (item.StatusId == (int)UserStatus.Active))
                                {
                                     <td class="text-center">
                                            <a href="@Url.Action("Edit", "AccountDetail", new {@id = item.Id})" id="btnModalOpen" title="Edit" data-placement="top" data-container="body">
                                                <i class="fa fa-edit icon"></i>&nbsp;Edit
                                            </a>
                                        </td>

                                    <td class="text-center">
                                        <a title="Delete" data-placement="top" data-container="body" onclick=" deleteConfirmation(updateStatus, '@item.Id', '@((int)UserStatus.Deleted)') ">
                                            <i class=" fa fa-trash-o text-danger">
                                            </i>&nbsp;Delete
                                        </a>
                                    </td>
                                }
                            </tr>
                            }
                        }
                        </tbody>
                    </table>
                </div>
            </section>
        </div>
    </div>
</section>

<script type="text/javascript">
    $(document).ready(function () {
        var exportColumns = $("#dt_userList > thead > tr > th").length;
        //console.log(exportColumns);
        var aTargets = [];
        for (var i = 0; i < exportColumns; i++) {
            aTargets.push(i * 1);
        }
        var visibleColumns = $("#dt_userList > thead > tr > th:not(.hidden)").length;
        //console.log(visibleColumns);
        var vTargets = [];
        for (var j = 0; j < visibleColumns; j++) {
            vTargets.push(j * 1);
        }
        $("#dt_userList").attr("exportColumn", aTargets);
        $("#dt_userList").attr("visibleColumn", vTargets);
        refreshGrid('dt_userList');
    });
    function updateStatus(id, statusId) {
        debugger;
        var token = $('input[name="__RequestVerificationToken"]').val();
        $.ajax({
            url: '@Url.Action("UpdateStatus","AccountDetail")',
            data: { Id: id, statusId: statusId, "__RequestVerificationToken": token },
            type: 'post',
            success: function(data) {
                location.reload();
            }

        });

    }

</script>