EduErp.Web/Controllers/CertificateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EduErp.Mvc.Utilities;
using EduErp.BO;
using EduErp.Common;

namespace EduErp.Web.Controllers
{
    public class CertificateController : BaseController
    {
        //
        // GET: /Certificate/

        public ActionResult Index()
        {
            return View(BLL.CertificateService.GetCertificates(SessionItems.SchoolId).Result);
        }
        public ActionResult Add()
        {
            var model = new BO.CertificationBo();
            model.ListOfCertificateTemplateType = BLL.CertificateService.GetCertificateTemplateType().Result;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(CertificationBo model)
        {
            if (!ModelState.IsValid)
            {
                model.ListOfCertificateTemplateType = BLL.CertificateService.GetCertificateTemplateType().Result;
                return View(model);
            }
            model.StatusId = (int)UserStatus.Active;
            model.CreatedBy = SessionItems.UserId;
            model.CreatedOn = System.DateTime.Now;
            model.SchoolId = SessionItems.SchoolId;
            var result = BLL.CertificateService.AddMapping(model).Result;
               if (result)
                    TempData["SuccessMessage"] = Messages.AddSuccessfully;
                else
                    TempData["ErrMessage"] = Messages.AddError;
                return Json(new { isErr = false, msg = Messages.AddSuccessfully }, JsonRequestBehavior.AllowGet);
        }
        [AjaxOnly]
        public ActionResult Edit(int id)
        {
            var result = BLL.CertificateService.GetCertificateById(id, SessionItems.SchoolId).Result;
            result.ListOfCertificateTemplateType = BLL.CertificateService.GetCertificateTemplateType().Result;
            return PartialView(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CertificationBo model)
        { 
            if(!ModelState.IsValid)
            {
                model.ListOfCertificateTemplateType=BLL.CertificateService.GetCertificateTemplateType().Result;
                return PartialView(model);
            }
            model.LastUpdatedBy=SessionItems.UserId;
            model.LastUpdatedOn=DateTime.Now;
            var result=BLL.CertificateService.UpdateCertificate(model).Result;
            if (result)
                TempData["SuccessMessage"] = Messages.UpdateSuccessfully;
            else
                TempData["ErrMessage"] = Messages.UpdateError;
            return Json(new { isErr = false, msg = Messages.UpdateSuccessfully }, JsonRequestBehavior.AllowGet);

        }

        [AjaxOnly]
        public JsonResult GetCertificateTemplateNameByTemplateTypeId(string templateTypeId)
        {
            var templateNameList = (from s in BLL.CertificateService.GetCertificateTemplateNameByTeplateTypeId(int.Parse(templateTypeId)).Result
                                select new SelectListItem()
                                {
                                    Text = s.Name,
                                    Value = s.Id.ToString()
                                }).ToList();
            return Json(templateNameList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult UpdateStatus(int id, int statusId)
        {
            var result = BLL.CertificateService.UpdateStatus(id, statusId, SessionItems.UserId).Result;
            if (result)
                TempData["SuccessMessage"] = Messages.UpdateSuccessfully;
            else
                TempData["ErrMessage"] = Messages.UpdateError;
            return Json(result);
        }


        public ActionResult Download()
        {
            DownloadBo model = new DownloadBo
            {
                //ListOfSessions = SessionlList,
                ListOfClasses = BLL.FeeTransactionService.GetClasses(SessionItems.SchoolId).Result,
                ListOfTemplateName=BLL.CertificateService.GetTemplateList(SessionItems.SchoolId).Result
                
            };
            return PartialView(model);
        }
        [HttpPost]
        public JsonResult GenerateCertificate(string classId, string sectionId, string studentId, string templateId)
        {
            var result = BLL.CertificateService.GetTemplate(SessionItems.SessionId, int.Parse(classId), int.Parse(sectionId), int.Parse(studentId), int.Parse(templateId), SessionItems.SchoolId).Result;
            return Json(result);
        }
        [AjaxOnly]
        public JsonResult GetSectionList(string classId)
        {
            var sectionList = (from a in BLL.FeeTransactionService.GetSections(int.Parse(classId)).Result
                               select new SelectListItem()
                               {
                                   Text = a.Name,
                                   Value = a.Id.ToString()
                               }).ToList();

            return Json(sectionList);
        }
        [AjaxOnly]
        public JsonResult GetStudentsListBySectionId(string sectionId)
        {
            var studentsList = (from s in BLL.FeeTransactionService.GetStudentsBySectionId(int.Parse(sectionId),SessionItems.SessionId).Result
                                select new SelectListItem()
                                {
                                    Text = s.Name,
                                    Value = s.Id.ToString()
                                }).ToList();
            return Json(studentsList);
        }

    }
}

EduErp.Web/Controllers/ExamController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using EduErp.BLL;
using EduErp.BO;
using EduErp.Common;
using EduErp.Mvc.Utilities;

namespace EduErp.Web.Controllers
{
    public class ExamController : BaseController
    {
        //
        // GET: /Exam/

        public ActionResult Index()
        {
            return View(ExamService.GetExams(SessionItems.SchoolId).Result);
        }

        public ActionResult Add()
        {
            var model = new ExamBo
            {
                ListOfSubjects = EmployeeService.GetSubjects(SessionItems.SchoolId).Result,
                ListOfSessions=SessionlList
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ExamBo model)
        {
            if (!ModelState.IsValid)
            {
                model.ListOfSubjects = EmployeeService.GetSubjects(SessionItems.SchoolId).Result;
                return Json(new { isErr = true, msg = ModelState.Values.SelectMany(x => x.Errors).ToArray().First().ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
            model.SchoolId = SessionItems.SchoolId;
            model.CreatedOn = DateTime.Now;
            model.CreatedBy = SessionItems.UserId;
            model.StatusId = (int)UserStatus.Active;

            var result = ExamService.AddExam(model).Result;
            if (result == 1)
            {
                TempData["SuccessMessage"] = Messages.AddSuccessfully;
                return Json(new { isErr = false, errMsg = Messages.AddSuccessfully }, JsonRequestBehavior.AllowGet);
            }
            return Json(result == -1 ? new { isErr = true, errMsg = Messages.ExistError } : new { isErr = true, errMsg = Messages.AddError }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var res = ExamService.GetExamById(id, SessionItems.SchoolId).Result;
            res.ListOfSubjects = EmployeeService.GetSubjects(SessionItems.SchoolId).Result;
            res.ListOfSessions = SessionlList;
            return View(res);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ExamBo model)
        {
            if (!ModelState.IsValid)
            {
                model.ListOfSubjects = EmployeeService.GetSubjects(SessionItems.SchoolId).Result;
                return Json(new { isErr = true, msg = ModelState.Values.SelectMany(x => x.Errors).ToArray().First().ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
            model.SchoolId = SessionItems.SchoolId;
            model.LastUpdatedOn = DateTime.Now;
            model.LastUpdatedBy = SessionItems.UserId;
            var result = ExamService.UpdateExam(model).Result;
            if (result)
                TempData["SuccessMessage"] = Messages.UpdateSuccessfully;
            else
                TempData["ErrMessage"] = Messages.AddError;
            return Json(new { isErr = false, msg = Messages.UpdateSuccessfully }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult UpdateStatus(int id, int statusId)
        {
            var result = ExamService.UpdateStatus(id, statusId, SessionItems.UserId).Result;
            if (result)
                TempData["SuccessMessage"] = Messages.UpdateSuccessfully;
            else
                TempData["ErrMessage"] = Messages.UpdateError;
            return Json(result);
        }

    }
}

EduErp.Web/Views/Certificate/Add.cshtml
@using EduErp.BO
@using EduErp.Mvc.Utilities
@using EduErp.Web.Utilities
@model EduErp.BO.CertificationBo
@{
    ViewBag.Title = "Mapping";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="panel panel-default scrollable">
    <header class="panel-heading font-bold">
        <div class="row">
            <div class="col-md-12">
                Mapping
            </div>
        </div>
    </header>
    @using (Html.BeginForm("Add", "Certificate", FormMethod.Post, new {enctype = "multipart/form-data", data_validate = "parsley", id = "MappingCertificate"}))
    {
        @Html.AntiForgeryToken()
        <div style="padding-top: 5px">
            <p style="margin-left: 12px">Fields with <span class="text-danger">*</span> are required.
            </p>
        </div>
        <div class="panel-body">
            <div class="pull-in clearfix">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Certificate TemplateType")
                            @Html.DropDownListFor(u => u.CertificateTemplateId, new SelectList(Model.ListOfCertificateTemplateType, "Id", "Name"), "Select Template", new {id = "TemplateType", @class = "form-control", data_parsley_required = "true", data_parsley_error_message = "Please Select Template"})
                        </div>
                        <div class="form-group col-md-3 col-sm-3">
                            @Html.Label("Template Name")
                           <select id="TemplateTypeName" required="required" class="form-control"></select>
                            @Html.HiddenFor(a => a.CertificateTemplateId, new {@id="hdnTemplateId" })
                        </div>
                        <div class=" form-group col-md-3 col-sm-3 col-xs-3" style="padding-top: 23px">
                            <button type="button" class="btn btn-s-md btn-lightGreen " id="AddButton">Add</button>
                        </div>
                    </div>
                </div>
                <div class="row scrollable" style="max-height: 250px;">
                    <div class="form-group col-md-12 col-sm-12">
                        <table class="table table-striped responsive" id="AddList">
                            <thead>
                            <tr>
                                <th class="text-center"title="Certificate Template Type" >Certificate TemplateType</th>
                                <th class="text-center" title="Template Name">Template Name</th>
                                <th class="text-center" title="Delete">Delete</th>

                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td id="TemplateType" class="text-center"></td>
                                <td id="TemplateName" class="text-center"></td>
                                <td id="Delete" class="text-center"></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>

        <footer class="panel-footer text-right bg-white lter">
            <button id="btnAddCertificate" type="button" class="btn btn-lightGreen btn-s-xs" onclick=" saveForm(); ">
                <i class="fa fa-save"></i>&nbsp;Save
            </button>
            <a href="@Url.Action("Index", "Certificate")" class="btn btn-s-md  btn-default">
                <i class="fa fa-ban"></i>&nbsp;Cancel
            </a>
        </footer>
    }
</section>
<script type="text/javascript">
    var counter = 0;
    $(document).ready(function () {
        //FOR SEARCH BOX IN DROPDOWN
        $('.chosen-select').chosen({
            search_contains: true
        });
        $("#TemplateType").change(function () {
            debugger;
            getCertificateName($("#TemplateType option:selected").val());
            //if (document.getElementById('TemplateType').selectedIndex !== 0) {
            //    $("#hdnTemplateId").val($("#TemplateType option:selected").val());

            //}
        });
       
        //DELETE ROW FROM MAPPING GRID
        $(document).on("click", ".deleteContact", function () {
            debugger;
            counter--;
            $(this).closest("tr").remove(); // closest used to remove the respective 'tr'   
        });
        //ADD ROW ON CLICK ADD BUTTON
        $("#AddButton").click(function () {
            debugger;
            if ($("#TemplateType option:selected").val() != 0 && $("#TemplateTypeName option:selected").val() != 0) {

                $("#btnAddCertificate").prop('disabled', false)
                addRow();
            } else {
                toastr.error("Please Select fields")
            }
        });
    });
    $("#btnAddCertificate").prop('disabled',true)
    //ADD ROW IN MAPPING GRID
    function addRow() {
        debugger;
        var html =  '<tr>'+'<td class="text-center">' + $("#TemplateType option:selected").text() + '<input type="hidden" value="' + $("#TemplateType option:selected").val() + '" name="MappingList[' + counter + '].TemplateTypeId" id="MappingList_' + counter + '_TemplateTypeId"' +
           '</td>' + '<td class="text-center">' + $("#TemplateTypeName option:selected").text() + '<input type="hidden" value="' + $("#TemplateTypeName option:selected").val() + '" name="MappingList[' + counter + '].TemplateId" id="MappingList_' + counter + '_TemplateId"' +
            '</td>' + '<td class="text-center">' + '<button type="button" id="btnDelete" class="text-center deleteContact btn btn btn-danger btn-xs">Remove</button>' + '</td>' + '</tr>';
        $(html).appendTo($("#AddList"));
        counter++;
    }

   
    //get certificatetypeName Based on typeId
    function getCertificateName(templateTypeId) {
        debugger;
        $("#TemplateTypeName").empty();
        if (templateTypeId != "") {
            $.ajax({
                type: 'post',
                url: '@Url.Action("GetCertificateTemplateNameByTemplateTypeId")',
                datatype: 'json',
                data: { templateTypeId: templateTypeId },
                success: function (templates) {
                    $.each(templates, function (i, cname) {
                        $("#TemplateTypeName").append('<option value="' + cname.Value + '">' + cname.Text + '</option>').prop('selected', true);
                    });
                    $("#TemplateTypeName option").eq(0).before($("<option></option>").val("0").text(" Please Select"));
                    $('#TemplateTypeName option[value="0"]').prop('selected', true);
                    @* $("#Student").val('@Model.StudentId');*@
                },

                error: function (ex) {
                    alert('Failed to retrieve classes.' + ex);
                }
            });
        }
    }
    function saveForm() {
        debugger;
        $('#MappingCertificate').parsley().validate();
        if ($('#MappingCertificate').parsley().isValid()) {

            var token = $('input[name="__RequestVerificationToken"]').val();
            var headers = {};
            headers['__RequestVerificationToken'] = token;
            $.ajax({
                url: '@Url.Action("Add", "Certificate")',
                data: $("#MappingCertificate").serialize(),
                type: 'post',
                header: headers,
                success: function (data) {
                    if (data.isErr) {
                        toastr.error(data.errMsg);
                        return;
                    }
                    window.location.href = '@Url.Action("Index","Certificate")';
                }
            });

        }
        else {
            toastr.error("Mandatory fields are required");
        }
    }
</script>

EduErp.Web/Views/Certificate/Edit.cshtml
@model EduErp.BO.CertificationBo

<div class="modal fade in" id="addFranchiseModal" style="display: block;" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button data-dismiss="modal" class="close" type="button">
                    ×
                </button>
                <h4 class="modal-title">
                    <span id="franchiseModalTitle">Update Certificate </span>
                </h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Edit", "Certificate", null, FormMethod.Post, new { data_validate = "parsley", @autocomplete = "off", @id = "updateCertificate" }))
                {
                    @Html.AntiForgeryToken()
                     <div class="panel-body">
                        <div class=" pull-in clearfix">
                            <div class="form-group col-md-12">
                                @Html.Label("CertificateTemplate Type")
                                @Html.DropDownListFor(a => Model.CertificateTemplateTypeId, new SelectList(Model.ListOfCertificateTemplateType, "Id", "Name"),"Please Select", new { @id="CertificateType",@class = "form-control", data_parsley_required = "true", data_parsley_error_message = "Please Select Template"})
                            </div>
                           <div class="form-group col-md-12">
                                @Html.Label("CertificateTemplate Name")
                               <select id="TemplateTypeName" required="true" class="form-control"></select>
                               @Html.HiddenFor(a => a.CertificateTemplateId, new { @id="CertificateTemplate"})
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button id="btnAddSession" type="button" class="btn btn-lightGreen btn-s-xs" onclick="updateCertificate();">
                            <i class="fa fa-save"></i>&nbsp;Update
                        </button>
                        <a data-dismiss="modal" class="btn btn-default" href="#">Cancel</a>
                    </div>
                }
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
</div>

<script src="~/Content/js/jquery-2.1.3.min.js"></script>
<script src="~/Content/js/parsley/parsley.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        $("#CertificateType").change(function () {
            debugger;
            getCertificateName($("#CertificateType option:selected").val());
        });
        getCertificateName(@Model.CertificateTemplateTypeId)
    });

    //get certificatetypeName Based on typeId
    function getCertificateName(templateTypeId) {
        debugger;
        $("#TemplateTypeName").empty();
        $.ajax({
            type: 'post',
            url: '@Url.Action("GetCertificateTemplateNameByTemplateTypeId")',
            datatype: 'json',
            data: { templateTypeId: templateTypeId },
            success: function (templates) {
                $.each(templates, function (i, cname) {
                    $("#TemplateTypeName").append('<option value="' + cname.Value + '">' + cname.Text + '</option>').prop('selected', true);
                });
                $("#TemplateTypeName option").eq(0).before($("<option></option>").val("0").text(" Please Select"));
                $('#TemplateTypeName option[value="0"]').prop('selected', true);
                $("#TemplateTypeName").val('@Model.CertificateTemplateId');
            },

            error: function (ex) {
                alert('Failed to retrieve classes.' + ex);
            }
        });
    }
    function updateCertificate() {
        $('#updateCertificate').parsley().validate();
        if ($('#updateCertificate').parsley().isValid()) {
            $('#CertificateTemplate').val($('#TemplateTypeName option:selected').val())
            var token = $('input[name="__RequestVerificationToken"]').val();
            var headers = {};
            headers['__RequestVerificationToken'] = token;
            $.ajax({
                url: '@Url.Action("Edit", "Certificate")',
                data: $("#updateCertificate").serialize(),
                type: 'post',
                header: headers,
                success: function (data) {
                    if (data.isErr) {
                        toastr.error(data.errMsg);
                        return;
                    }
                    window.location.href = '@Url.Action("Index", "Certificate")';
                }
            });

        }
        else {
            toastr.error("Please fill all required fields.");
        }
    }
</script>

EduErp.Web/Views/Certificate/Index.cshtml
@using EduErp.BO
@using EduErp.BO.Enumerators
@using EduErp.Mvc.Utilities
@model List<CertificationBo>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_GridLayout.cshtml";
}

<header class="panel-heading font-bold b-light">
    Mapping
    @if (SessionItems.UserRights.Any(a => a.MenuId == (int)MenuMasters.Certificate) && SessionItems.UserRights.Any(a => a.RightId == (int)Right.Write))
    {
        <a href="@Url.Action("Add", "Certificate")" class="btn-sm btn-primary pull-right" ><i class="fa fa-plus"></i>&nbsp;Map certificate to school</a>
    }
</header>
@Html.AntiForgeryToken()
<section class="scrollable w-f">
    <div class="row">
        <div class="col-md-12">
            <section class="panel panel-default">
                <div class="table-responsive">
                    <table  id="dt_userList" class="table table-striped " title="Certificate" width="100%" exportcolumn="0,1" visiblecolumn="0,1,2,3" lastunsortcount="3">
                        <thead class="bg-primary">
                            <tr class="active text-white">
                                <th class="text-center" title="Certificate Type Name">
                                    CertificateType Name
                                </th>
                                <th class="text-center" title="Certificate Name">
                                    Certificate Name
                                </th>
                                <th class="text-center" title="Status">
                                    Status
                                </th>
                                 @if (SessionItems.UserRights.Any(a => a.MenuId == (int)MenuMasters.Exam) && SessionItems.UserRights.Any(a => a.RightId == (int)Right.Write))
                                 {
                                     <th class="text-center" title="Action">
                                         Action</th>
                                 }
                            </tr>
                        </thead>

                        <tbody>
                            @if (Model != null && Model.Count > 0)
                            {

                                foreach (var item in Model)
                                {

                                    <tr>
                                        <td class="text-center">
                                            @item.CertificateTemplateTypeName
                                        </td>
                                        <td class="text-center">
                                            @item.CertificateTemplateName
                                        </td>
                                        <td class="text-center">
                                            <span class="hidden">@item.StatusId</span>
                                            <div id="btn_@item.Id">
                                                <button class="btn btn-default @(item.StatusId == (int)UserStatus.Active ? "btn-success active " : "")" title="@(item.StatusId == (int)UserStatus.Active ? "Click To Deactivate" : "Click To Activate")" data-container="body" data-toggle="tooltip"
                                                        id="@item.Id" onclick=" setStatusConfirmation(updateStatus, '@(item.StatusId == (int)UserStatus.Active ? "Deactivate Certificate" : "Activate Certificate ?")', '@(item.StatusId == (int)UserStatus.Active ? "Are you sure you want to Deactivate Certificate ?" : "Are you sure you want to Activate Certificate ?")', '@item.Id', '@(item.StatusId == (int)UserStatus.Active ? (int)UserStatus.InActive : (int)UserStatus.Active)') ">
                                                    <i class="fa @(item.StatusId == (int)UserStatus.Active ? "fa-check text-active" : "fa-times text-danger") "></i>
                                                    <span class=@(item.StatusId == (int)UserStatus.Active ? "text-active" : "text")>@(item.StatusId == (int)UserStatus.Active ? "Active" : "Inactive")</span>
                                                </button>
                                            </div>
                                        </td>
                                        
                                      @*  <td class="text-center">
                                            @if ((SessionItems.UserRights.Any(a => a.MenuId == (int) MenuMasters.Certificate) && SessionItems.UserRights.Any(a => a.RightId == (int) Right.Write)) && (item.StatusId == (int) UserStatus.Active))
                                            {
                                                <a href="@Url.Action("Edit", "Certificate", new {@id = item.Id})" id="btnModalOpen" ajax-modal="ajaxModal" title="Edit">
                                                    <i class="fa fa-edit icon"></i>&nbsp;Edit
                                                </a>
                                               
                                            }
                                        </td>
                                        <td class="text-center">
                                            @if ((SessionItems.UserRights.Any(a => a.MenuId == (int) MenuMasters.Certificate) && SessionItems.UserRights.Any(a => a.RightId == (int) Right.Write)) && (item.StatusId == (int) UserStatus.Active))
                                            {
                                                <a title="Delete" data-placement="top" data-container="body" onclick=" deleteConfirmation(updateStatus, '@item.Id', '@((int) UserStatus.Deleted)') ">
                                                    <i class=" fa fa-trash-o text-danger">
                                                    </i>&nbsp;Delete
                                                </a>
                                            }
                                        </td>*@
                                         <td class="text-center">
                                      @if ((SessionItems.UserRights.Any(a => a.MenuId == (int) MenuMasters.Certificate) && SessionItems.UserRights.Any(a => a.RightId == (int) Right.Write)) && (item.StatusId == (int) UserStatus.Active))
                                            {
                                                <a href="@Url.Action("Edit", "Certificate", new {@id = item.Id})" id="btnModalOpen" ajax-modal="ajaxModal" title="Edit">
                                                    <i class="fa fa-edit icon"></i>
                                                </a>
                                               
                                            }
                                             &nbsp;
                                             @if ((SessionItems.UserRights.Any(a => a.MenuId == (int) MenuMasters.Certificate) && SessionItems.UserRights.Any(a => a.RightId == (int) Right.Write)) && (item.StatusId == (int) UserStatus.Active))
                                            {
                                                <a title="Delete" data-placement="top" data-container="body" onclick=" deleteConfirmation(updateStatus, '@item.Id', '@((int) UserStatus.Deleted)') ">
                                                    <i class=" fa fa-trash-o text-danger">
                                                    </i>
                                                </a>
                                            }
                                         </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </section>
        </div>
    </div>
</section>

<script type="text/javascript">
    $(document).ready(function () {
        var exportColumns = $("#dt_userList > thead > tr > th").length;
        //console.log(exportColumns);
        var aTargets = [];
        for (var i = 0; i < exportColumns; i++) {
            aTargets.push(i * 1);
        }
        var visibleColumns = $("#dt_userList > thead > tr > th:not(.hidden)").length;
        //console.log(visibleColumns);
        var vTargets = [];
        for (var j = 0; j < visibleColumns; j++) {
            vTargets.push(j * 1);
        }
        $("#dt_userList").attr("exportColumn", aTargets);
        $("#dt_userList").attr("visibleColumn", vTargets);
        refreshGrid('dt_userList');
    });
    @*function edit(id) {
        window.location.href = '@Url.Action("Edit","Exam")'+'/'+id;
       
    }*@
    function updateStatus(id, statusId) {
        debugger;
        var token = $('input[name="__RequestVerificationToken"]').val();
        $.ajax({

            url: '@Url.Action("UpdateStatus","Certificate")',
            data: { id: id, statusId: statusId, "__RequestVerificationToken": token },
            type: 'post',
            success: function () {
                //toastr.success(data);
                location.reload();
            }

        });

    }

</script>