EduErp.Web/Controllers/OnlineTestQuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EduErp.BO;
using EduErp.Common;
using EduErp.Mvc.Utilities;
using EduErp.BLL;
using System.IO;

namespace EduErp.Web.Controllers
{
    public class OnlineTestQuestionController : BaseController
    {
        //
        // GET: /OnlineTestQuestion/

        public ActionResult Index()
        {
            var subjectList = OnlineTestQuestionService.GetSubjects(SessionItems.SchoolId).Result;
            var OnlineTestQuestion = new OnlineExamTestQuestionBo
            {
                ListOfSubject = subjectList,
                
            };
            return View(OnlineTestQuestionService.GetOnlineTestQuestion(SessionItems.SchoolId).Result);
        }
        public ActionResult Add()
        {
            var ListOfQuestionTypeId = OnlineTestQuestionService.GetQuestionTypeId().Result;
            var subjectList = OnlineTestQuestionService.GetSubjects(SessionItems.SchoolId).Result;
            var OnlineTestQuestion = new OnlineExamTestQuestionBo
            {
                ListOfSubject = subjectList,
                ListOfQuestionType = ListOfQuestionTypeId,
            };
            return View(OnlineTestQuestion);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(OnlineExamTestQuestionBo model, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                //model.ListOfSchools = Schools;
                return Json(new { isErr = true, msg = ModelState.Values.SelectMany(x => x.Errors).ToArray().First().ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
            if (file != null && file.ContentLength > 0)
            {
                var uploadDir = "~/Temp";
                var imagePath = Path.Combine(Server.MapPath(uploadDir), file.FileName);
                var imageUrl = Path.Combine(uploadDir, file.FileName);
                file.SaveAs(imagePath);
                model.ImagePath = imageUrl;
            }
            model.SchoolId = SessionItems.SchoolId;
            model.CreatedOn = DateTime.Now;
            model.CreatedBy = SessionItems.UserId;
            model.Status = (int)UserStatus.Active;
            //model.ListOfSchools = Schools;
            var result = OnlineTestQuestionService.AddOnlineTestQuestion(model).Result;
            if (result > 0)
            {
                TempData["SuccessMessage"] = Messages.AddSuccessfully;
                return Json(new { isErr = false, errMsg = Messages.AddSuccessfully }, JsonRequestBehavior.AllowGet);
            }
            return Json(result == -1 ? new { isErr = true, errMsg = Messages.ExistError } : new { isErr = true, errMsg = Messages.AddError }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult UpdateStatus(int id, int status)
        {
            var result = OnlineTestQuestionService.UpdateStatus(id, status, SessionItems.UserId).Result;
            if (result)
                TempData["SuccessMessage"] = Messages.UpdateSuccessfully;
            else
                TempData["ErrMessage"] = Messages.UpdateError;
            return Json(result);
        }
        [AjaxOnly]
        public ActionResult Edit(int id)
        {
            var result = OnlineTestQuestionService.GetOnlineTestQuestionById(id).Result;
            var ListOfQuestionTypeId = OnlineTestQuestionService.GetQuestionTypeId().Result;
            var subjectList = OnlineTestQuestionService.GetSubjects(SessionItems.SchoolId).Result;
            var model = new OnlineExamTestQuestionBo
            {
                
               Description= result.Description,
               Questions = result.Questions,
               SubjectId = result.SubjectId,

                ListOfQuestionType = ListOfQuestionTypeId,
                ListOfSubject = subjectList,
                //ListOfQuestionType = result.ListOfQuestionType,
               QuestionTypeId = result.QuestionTypeId,
               Ismcq = result.Ismcq,
                Status = result.Status,
                SchoolId = result.SchoolId
            };
            return PartialView(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OnlineExamTestQuestionBo model)
        {

            if (!ModelState.IsValid)
            {
                //model.ListOfSchools = Schools;
                return Json(new { isErr = true, msg = ModelState.Values.SelectMany(x => x.Errors).ToArray().First().ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
            model.SchoolId = SessionItems.SchoolId;
            model.Status = (int)UserStatus.Active;
            model.LastUpdatedBy = SessionItems.UserId;
            model.LastUpdatedOn = DateTime.Now;
            var result = OnlineTestQuestionService.UpdateOnlineTestQuestion(model).Result;
            if (result)
                TempData["SuccessMessage"] = Messages.UpdateSuccessfully;
            else
                TempData["ErrMessage"] = Messages.UpdateError;
            return Json(new { isErr = false, msg = Messages.UpdateSuccessfully }, JsonRequestBehavior.AllowGet);

        }
    }
}

EduErp.Web/Views/OnlineTestQuestion/Add.cshtml
@using EduErp.BO
@using EduErp.Mvc.Utilities
@model  EduErp.BO.OnlineExamTestQuestionBo
<div class="modal fade in" id="addOnlineTestModal" style="display:block;" aria-hidden="false">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button data-dismiss="modal" class="close" type="button">
                    x
                </button>
                <h4 class="modal-title">
                    <span id="OnlineTestModalTitle"> Add OnlineTest Question</span>
                </h4>
            </div>

            <div class="modal-body">
                @using (Html.BeginForm("Add", "OnlineTestQuestion", null, FormMethod.Post, new { data_validate = "parsley", @autocomplete = "off", @id = "addOnline" }))
                {
                    @Html.AntiForgeryToken()
                    <div style="padding-top: 5px">
                  <p style="margin-left: 8px">Fields with <span class="text-danger">*</span> are required. </p>
                  </div>
                    <div class="panel-body">
                        <div class=" pull-in clearfix">
                            <div class="row">
                            @*<div class=" form-group col-md-6 col-sm-6 col-xs-6">
                                @Html.LabelFor(m => m.Name)&nbsp;<span class="text-danger">*</span>
                                @Html.TextBoxFor(m => m.Name, new { @class = "form-control",maxlength="100", data_parsley_required = "true", data_parsley_error_message = "Enter Name" })
                            </div>*@
                           <div class="form-group col-md-6 col-sm-6 col-xs-6">
                                    @Html.Label("Subject Name")&nbsp;<span class="text-danger">*</span>
                                 @Html.DropDownListFor(m => m.SubjectId, new SelectList(Model.ListOfSubject, "Id", "Name"), "Please Select", new {@class = "form-control chosen-select", data_parsley_required = "true", data_parsley_error_message = "Please Enter Subject Name"})
                                   @* @Html.TextBoxFor(m => m.SubjectId, new { @class = "form-control"})*@
                                   </div>
                           <div class="form-group col-md-6 col-sm-6 col-xs-6">
                                    @Html.Label("Question")&nbsp;<span class="text-danger">*</span>
                                    @Html.TextBoxFor(m => m.Questions, new { @class = "form-control", data_parsley_required = "true", data_parsley_error_message = "Please Enter Questions"})
                                   </div>
                                </div>
                            
                            <div class="row">
                                <div class="form-group col-md-6 col-sm-6 col-xs-6">
                                    @Html.Label("Question Type")&nbsp;<span class="text-danger">*</span>
                                    @Html.DropDownListFor(m => m.QuestionTypeId, new SelectList(Model.ListOfQuestionType, "Id", "Name"), "Please Select", new {@class = "form-control chosen-select",@id="QuestionTypeId", data_parsley_required = "true", data_parsley_error_message = "Please Enter Question Type"})
                                 </div>
                                <div class="form-group col-md-6 col-sm-6 col-xs-6">
                                    @Html.Label("Description")
                                    @Html.TextBoxFor(m => m.Description, new { @class = "form-control ",maxlength="100"})
                                   </div>
                               
                               
                            </div>

                     
                                <div class="row">
                            
                           
                             <div class="form-group col-md-6 col-sm-6 col-xs-6" id="BrowseHide">
                                   
                                <input type="file" class="form-control" name="file">
                            </div>
                           <div class="form-group col-md-2 col-sm-2 col-xs-2">
                                    @Html.Label("Ismcq")
                                   @Html.CheckBoxFor(m => m.Ismcq, new { @class="form-control"})
                                  
                               </div>
                                </div>
                            
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button id="btnAddOnlineTest" type="button" class="btn btn-lightGreen btn-s-xs" onclick="saveForm();">
                            <i class="fa fa-save"></i>&nbsp; Save
                        </button>
                        <a data-dismiss="modal" class="btn btn-default" href="#">Cancel</a>

                    </div>

                }
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#QuestionTypeId").change(function () {
            debugger;
            if ($("#QuestionTypeId").val() == 1) {
                $("#BrowseHide").show();

            } else {

                $("#BrowseHide").hide();

            }
        })
        });
   
    function saveForm() {
        debugger;
        $('#addOnline').parsley().validate();
        if ($('#addOnline').parsley().isValid()) {

            var token = $('input[name="__RequestVerificationToken"]').val();
            var headers = {};
            headers['__RequestVerificationToken'] = token;
            $.ajax({
                url: '@Url.Action("Add", "OnlineTestQuestion")',
                data: $("#addOnline").serialize(),
                type: 'post',
                header: headers,
                success: function (data) {
                    if (data.isErr) {
                        toastr.error(data.errMsg);
                        return;
                    }
                    window.location.href = '@Url.Action("Index", "OnlineTestQuestion")';
                }
            });

        }
        else {
            toastr.error("Mandatory fields are required");
        }
    }
    

</script>

EduErp.Web/Views/OnlineTestQuestion/Edit.cshtml
@using EduErp.BO
@using EduErp.Mvc.Utilities
@model EduErp.BO.OnlineExamTestQuestionBo


<div class="modal fade in" id="addFranchiseModal" style="display: block;" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button data-dismiss="modal" class="close" type="button">
                    ×
                </button>
                <h4 class="modal-title">
                    <span id="franchiseModalTitle">Update @Level.GetlabelName((int)LabelEnum.OnlineTestQuestion)</span>
                </h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Edit", "OnlineTestQuestion", null, FormMethod.Post, new { data_validate = "parsley", @autocomplete = "off", @id = "editclass" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(m => m.Id)
                    <div style="padding-top: 5px">
                  <p style="margin-left: 8px">Fields with <span class="text-danger">*</span> are required. </p>
                  </div>
                    <div class="panel-body">
                        <div class=" pull-in clearfix">
                            <div class="row">
                            @*<div class=" form-group col-md-6 col-sm-6 col-xs-6">
                                @Html.LabelFor(m => m.Name)&nbsp;<span class="text-danger">*</span>
                                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", data_parsley_required = "true",maxlength="100" ,data_parsley_error_message = "Please enter name" })
                            </div>*@
                           
                             
                                </div>
                            <div class="row">
                                 <div class=" form-group col-md-6 col-sm-6 col-xs-6">
                                @Html.LabelFor(m => m.SubjectName)&nbsp;<span class="text-danger">*</span>
                                      
                              
                                @Html.DropDownListFor(m => m.SubjectId, new SelectList(Model.ListOfSubject, "Id", "Name"), new { @class="form-control chosen-select"})
                              @*  @Html.TextBoxFor(m => m.SubjectId, new { @class = "form-control", data_parsley_required = "true" ,data_parsley_error_message = "Please enter subjectId" })*@
                            </div>
                             <div class=" form-group col-md-6 col-sm-6 col-xs-6">
                                @Html.LabelFor(m => m.Questions)&nbsp;<span class="text-danger">*</span>
                                @Html.TextBoxFor(m => m.Questions, new { @class = "form-control", data_parsley_required = "true",data_parsley_error_message = "Please enter Question" })
                            </div>
                           
                                </div>
                            <div class="row">
                            <div class=" form-group col-md-6 col-sm-6 col-xs-6">
                                @Html.Label("Question Type")&nbsp;<span class="text-danger">*</span>
                              
                          @Html.DropDownListFor(m => m.QuestionTypeId, new SelectList(Model.ListOfQuestionType, "Id", "Name"),new {@class = "form-control chosen-select"})
                               
                            </div>
                                
                            <div class=" form-group col-md-6 col-sm-6 col-xs-6">
                                @Html.LabelFor(m => m.Ismcq)
                                @Html.TextBoxFor(m => m.Ismcq, new { @class = "form-control", data_parsley_required = "true" ,data_parsley_error_message = "Please enter ismcq" })
                            </div>
                                </div>
                            <div class="row">
                             <div class=" form-group col-md-6 col-sm-6 col-xs-6">
                               
                                @Html.TextBoxFor(m => m.Description, new { @class = "form-control",maxlength="250" })
                            </div>
                                </div>
                            @*@if (SessionItems.IsSuperAdmin)
                            {
                                <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                   @Level.GetlabelName((int)LabelEnum.School)&nbsp;<span class="text-danger">*</span>
                                    @Html.DropDownListFor(m => m.SchoolId, new SelectList(Model.ListOfSchools, "Value", "Text"), new { @class = "form-control chosen-select", data_parsley_required = "true" })
                                </div>
                            }
                            else
                            {
                                <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                   @Level.GetlabelName((int)LabelEnum.School)&nbsp;<span class="text-danger">*</span>
                                    @Html.TextBoxFor(m => Model.ListOfSchools.FirstOrDefault(a => a.Value == SessionItems.SchoolId.ToString()).Text, new { @class = "form-control", @readonly = "readonly",data_parsley_required = "true" })
                                    @Html.HiddenFor(m => m.SchoolId)
                                </div>
                            }*@
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button id="btnEditClass" type="button" class="btn btn-lightGreen btn-s-xs" onclick="validateForm();">
                            <i class="fa fa-save"></i>&nbsp;Update
                        </button>
                        <a data-dismiss="modal" class="btn btn-default btn-s-xs" href="#">Cancel</a>
                    </div>
                }
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
</div>

<script type="text/javascript">

    function validateForm() {
        debugger;
        $('#editclass').parsley().validate();
        if ($('#editclass').parsley().isValid()) {
            var token = $('input[name="__RequestVerificationToken"]').val();
            var headers = {};
            headers['__RequestVerificationToken'] = token;
            $.ajax({
                url:'@Url.Action("Edit","OnlineTestQuestion")',
                data: $("#editclass").serialize(),
                type:'post',
                headers:headers,
                success: function (data) {
                    if (data.isErr) {
                        toastr.error(data.errMsg);
                        return;
                    }
                    window.location.href = '@Url.Action("Index", "OnlineTestQuestion")';
                }
            });
        }
        else {
            toastr.error("Mandatory fields are required");
        }
    }
</script>

EduErp.Web/Views/OnlineTestQuestion/Index.cshtml
@using EduErp.BO
@using EduErp.BO.Enumerators
@using EduErp.Mvc.Utilities
@model List<OnlineExamTestQuestionBo>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_GridLayout.cshtml";
}

<header class="panel-heading font-bold b-light">
    Online Test Question
    @if (SessionItems.UserRights.Any(a => a.MenuId == (int)MenuMasters.OnlineTestQuestion) && SessionItems.UserRights.Any(a => a.RightId == (int)Right.Write))
    {
        <a href="@Url.Action("Add", "OnlineTestQuestion")" class="btn-sm btn-primary pull-right" ajax-modal="ajaxModal"><i class="fa fa-plus"></i>&nbsp;Add OnlineTestQuestion</a>
    }
</header>
@Html.AntiForgeryToken()
<section class="scrollable w-f">
    <div class="row">
        <div class="col-md-12">
            <section class="panel panel-default">
                <div class="table-responsive">
                    <table id="dt_userList" class="table table-striped" title="OnlineTestQuestion" width="100%" exportcolumn="0,1,2" visiblecolumn="0,1,2,3">
                        <thead class="bg-primary">
                            <tr class="active text-white">
                                @*<th class="text-center" title="Name">
                                    Name
                                </th>*@
                             <th class="text-center" title="Subject Name">
                                 Subject Name
                                 </th>
                                
                                <th class="text-center" title="Question">
                                 Question
                                 </th>
                                
                                <th class="text-center" title="QuestionType">
                                 Question Type
                                 </th>
                                <th class="text-center" title="Ismcq">
                                Ismcq
                                 </th>
                                <th class="text-center" title="Description">
                                 Description
                                 </th>
                                <th class="text-center" title="Status">
                                    Status
                                </th>
                                 @if (SessionItems.UserRights.Any(a => a.MenuId == (int) MenuMasters.OnlineTestQuestion) && SessionItems.UserRights.Any(a => a.RightId == (int) Right.Write))
                                 {
                                     <th class="text-center" title="Action">
                                         Action</th>
                                 }
                            </tr>
                        </thead>

                        <tbody>
                            @if (Model != null && Model.Count > 0)
                            {

                                foreach (var item in Model)
                                {

                                    <tr>
@*                                        <td class="text-center">
                                            @item.Name
                                        </td>*@
                                        <td class="text-center">
                                            @item.SubjectName
                                        </td>
                                        
                                        <td class="text-center">
                                            @item.Questions
                                        </td>
                                        
                                        <td class="text-center">
                                            @item.QuestionType
                                        </td>
                                        <td class="text-center">
                                            @item.Ismcq
                                        </td>
                                        <td class="text-center">
                                            @item.Description
                                        </td>
                                      <td class="text-center">
                                            <span class="hidden">@item.Status</span>
                                            <div id="btn_@item.Id">
                                                <button class="btn btn-default @(item.Status == (int) UserStatus.Active ? "btn-success active " : "")" title="@(item.Status == (int) UserStatus.Active ? "Click To Deactivate" : "Click To Activate")" data-container="body" data-toggle="tooltip"
                                                        id="@item.Id" onclick=" setStatusConfirmation(updateStatus, '@(item.Status == (int) UserStatus.Active ? "Deactivate OnlineTestQuestion" : "Activate OnlineTestQuestion ?")', '@(item.Status == (int) UserStatus.Active ? "Are you sure you want to Deactivate OnlineTestQuestion ?" : "Are you sure you want to Activate OnlineTestQuestion ?")', '@item.Id', '@(item.Status == (int) UserStatus.Active ? (int) UserStatus.InActive : (int) UserStatus.Active)') ">
                                                    <i class="fa @(item.Status == (int) UserStatus.Active ? "fa-check text-active" : "fa-times text-danger") "></i>
                                                    <span class="@(item.Status == (int) UserStatus.Active ? "text-active" : "text")">@(item.Status == (int) UserStatus.Active ? "Active" : "Inactive")</span>
                                                </button>
                                            </div>
                                        </td>

                                        <td class="text-center">
                                             @if ((SessionItems.UserRights.Any(a => a.MenuId == (int) MenuMasters.OnlineTestQuestion) && SessionItems.UserRights.Any(a => a.RightId == (int) Right.Write)) && (item.Status == (int) UserStatus.Active))
                                            {
                                                <a href="@Url.Action("Edit", "OnlineTestQuestion", new {@id =item.Id})" id="btnModalOpen" title="Edit" data-placement="top" data-container="body" ajax-modal="ajaxModal">
                                                    <i class="fa fa-edit icon"></i>
                                                </a>
                                            }
                                            &nbsp;
                                         @if ((SessionItems.UserRights.Any(a => a.MenuId == (int) MenuMasters.OnlineTestQuestion) && SessionItems.UserRights.Any(a => a.RightId == (int) Right.Write)) && (item.Status == (int) UserStatus.Active))
                                            {
                                                <a title="Delete" data-placement="top" data-container="body" onclick=" deleteConfirmation(updateStatus, '@((int) item.Id)', '@((int) EduErp.BO.UserStatus.Deleted)') ">
                                                    <i class=" fa fa-trash-o text-danger">
                                                    </i>
                                                </a>
                                            }
                                        </td>
                                         
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    $(document).ready(function () {
        var exportColumns = $("#dt_userList > thead > tr > th:not(.notExport)").length;
        //console.log(exportColumns);
        var aTargets = [];
        for (var i = 0; i < exportColumns; i++) {
            aTargets.push(i * 1);
        }
        var visibleColumns = $("#dt_userList > thead > tr > th:not(.hidden)").length;
        //console.log(visibleColumns);
        var vTargets = [];
        for (var j = 0; j < visibleColumns; j++) {
            vTargets.push(j * 1);
        }
        $("#dt_userList").attr("exportColumn", aTargets);
        $("#dt_userList").attr("visibleColumn", vTargets);
        refreshGrid('dt_userList');
    });
    function updateStatus(id, status) {
        debugger;
        var token = $('input[name="__RequestVerificationToken"]').val();
        $.ajax({

            url: '@Url.Action("UpdateStatus", "OnlineTestQuestion")',
            data: { id: id, status: status, "__RequestVerificationToken": token },
            type: 'post',
            success: function () {
                //toastr.success(data);
                location.reload();
            }

        });

    }

</script>